export const SAFETY_CATEGORIES = [
  'Administrative',
  'Asbestos',
  'Behaviors',
  'Concrete Masonry',
  'Confined Space',
  'Cranes',
  'Demolition',
  'Electrical Safety',
  'Emergency Action Plan',
  'Exits/Egress',
  'Fall Protection',
  'Fire Safety',
  'Forklifts',
  'Fueling Operations',
  'Hazard Communication',
  'Health Hazards',
  'Heat Illness Prevention',
  'Housekeeping',
  'Infection Control',
  'Ladders/Stairs',
  'Laser Safety',
  'Mechanized Equipment',
  'Medical/FA Services',
  'MEWPS Group B Aerial Boom Lifts',
  'MEWPs Group A Scissor Lifts',
  'Overhead Hoists',
  'Pile Driving',
  'PPE',
  'Postings/Safety Signs',
  'Public Protection',
  'Recordkeeping',
  'Respiratory Protection',
  'Rigging',
  'Safety Training',
  'Sanitation',
  'Scaffolds - Rolling Baker',
  'Scaffolds - Supported',
  'Scaffolds - Suspension',
  'Scaffolds - Master Climber',
  'Scaffolds - Pump Jack',
  'Scaffolds - Stair Tower',
  'Silica Exposure',
  'Steel Erection',
  'Stilt Safety',
  'Storage and Disposal',
  'Stormwater Management',
  'Temporary Heating Devices',
  'Tools (Hand and Power)',
  'Tools (Powder Actuated)',
  'Traffic Control',
  'Traffic Control (Flaggers)',
  'Trenching/Excavation',
  'Trucks/Pickups/Autos',
  'Trucker/Trailer Combos DOT',
  'Welding and Cutting (Hot Work)',
  'Working Over Water',
  'Other/Misc.',
] as const

export type SafetyCategory = (typeof SAFETY_CATEGORIES)[number]
