import { Observation } from '@/types/audit'

export function generatePDFContent(
  observations: Observation[],
  auditInfo: {
    projectName?: string
    inspectorName?: string
    auditDate: string
  }
): string {
  const rows = observations
    .map((obs, index) => {
      const narrative =
        obs.compliance === 'compliant'
          ? obs.compliant_narrative
          : obs.non_compliant_narrative
      const corrective =
        obs.compliance === 'compliant'
          ? obs.compliant_corrective_action
          : obs.non_compliant_corrective_action
      const complianceLabel = obs.compliance === 'compliant' ? 'POS' : 'NEG'
      const complianceColor =
        obs.compliance === 'compliant' ? '#22c55e' : '#ef4444'

      return `
        <tr>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">${index + 1}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">
            <span style="background:${complianceColor};color:white;padding:2px 8px;border-radius:4px;font-size:12px;">${complianceLabel}</span>
          </td>
          <td style="padding:8px;border:1px solid #e5e7eb;">${obs.category}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;">${obs.osha_standard || ''}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;">${narrative || ''}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">${obs.severity}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;">${corrective || ''}</td>
        </tr>`
    })
    .join('')

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>SafetyLens AI - Audit Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #1f2937; }
        h1 { color: #f97316; margin-bottom: 4px; }
        .meta { color: #6b7280; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th { background: #f97316; color: white; padding: 10px 8px; text-align: left; border: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
      </style>
    </head>
    <body>
      <h1>SafetyLens AI — Audit Report</h1>
      <div class="meta">
        ${auditInfo.projectName ? `<strong>Project:</strong> ${auditInfo.projectName}<br>` : ''}
        ${auditInfo.inspectorName ? `<strong>Inspector:</strong> ${auditInfo.inspectorName}<br>` : ''}
        <strong>Date:</strong> ${auditInfo.auditDate}<br>
        <strong>Total Observations:</strong> ${observations.length}
      </div>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Status</th>
            <th>Category</th>
            <th>OSHA Ref</th>
            <th>Narrative</th>
            <th>Severity</th>
            <th>Corrective Action</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="text-align:center;color:#9ca3af;margin-top:30px;font-size:12px;">
        Generated by SafetyLens AI &mdash; safetylens.ai
      </p>
    </body>
    </html>
  `
}

export function printPDF(html: string) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  printWindow.print()
}
