import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Vorsa AI',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: March 11, 2026</p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-gray-600">
        <section>
          <h2 className="text-lg font-semibold text-gray-900">1. Acceptance of Terms</h2>
          <p className="mt-2">
            By accessing or using Vorsa AI (&quot;the Service&quot;), operated by OSO
            Construction Tech, you agree to be bound by these Terms of Service. If
            you do not agree to these terms, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">2. Description of Service</h2>
          <p className="mt-2">
            Vorsa AI is an AI-powered construction safety platform that provides
            photo analysis for hazard identification, OSHA standard citations, and
            an AI Safety Coach for guided safety walks. The Service is available at
            getvorsa.ai.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">3. Account Responsibilities</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>You must provide accurate and complete registration information.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You are responsible for all activity under your account.</li>
            <li>You must notify us immediately of any unauthorized use of your account.</li>
            <li>You must be at least 18 years old to use the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">4. Acceptable Use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Use the Service for any unlawful purpose.</li>
            <li>Upload content that violates any third-party rights.</li>
            <li>Attempt to reverse-engineer, decompile, or disassemble the Service.</li>
            <li>Interfere with or disrupt the Service or its infrastructure.</li>
            <li>Use automated tools to access the Service without our permission.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">5. Subscriptions &amp; Billing</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>
              The Service offers subscription plans billed monthly or annually
              through Stripe.
            </li>
            <li>
              Free trials are available for new accounts. No credit card is required
              to start a trial.
            </li>
            <li>
              Subscriptions automatically renew unless cancelled before the renewal
              date.
            </li>
            <li>
              Refunds are handled on a case-by-case basis. Contact us within 14
              days of a charge for refund requests.
            </li>
            <li>
              We reserve the right to change pricing with 30 days&apos; notice to
              existing subscribers.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">
            6. AI-Generated Content Disclaimer
          </h2>
          <div className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-900">
            <p className="font-medium">Important:</p>
            <p className="mt-1">
              Safety observations, hazard identifications, OSHA citations, and all
              other analysis generated by Vorsa AI are produced by artificial
              intelligence and are provided for informational purposes only. This
              content does not constitute professional safety advice, legal counsel,
              or a substitute for qualified safety inspections.
            </p>
            <p className="mt-2">
              All AI-generated observations should be reviewed, verified, and
              validated by qualified safety professionals before being relied upon
              for compliance, decision-making, or reporting purposes. OSO
              Construction Tech is not liable for any actions taken based solely on
              AI-generated content.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">7. Intellectual Property</h2>
          <p className="mt-2">
            You retain ownership of all photos and content you upload. By using the
            Service, you grant us a limited license to process your content for the
            purpose of providing the Service. We own all rights to the Vorsa AI
            platform, including its design, code, and AI models.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">8. Limitation of Liability</h2>
          <p className="mt-2">
            To the maximum extent permitted by law, OSO Construction Tech shall not
            be liable for any indirect, incidental, special, consequential, or
            punitive damages, including loss of profits, data, or business
            opportunities, arising from your use of the Service. Our total liability
            shall not exceed the amount paid by you in the twelve months preceding
            the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">9. Termination</h2>
          <p className="mt-2">
            We may suspend or terminate your access to the Service at any time for
            violation of these terms. You may cancel your account at any time
            through your account settings. Upon termination, your right to use the
            Service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">10. Governing Law</h2>
          <p className="mt-2">
            These Terms are governed by and construed in accordance with the laws of
            the State of California, without regard to its conflict of law
            provisions. Any disputes shall be resolved in the courts of California.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">11. Changes to Terms</h2>
          <p className="mt-2">
            We reserve the right to modify these Terms at any time. We will provide
            notice of material changes by updating the &quot;Last updated&quot; date.
            Continued use of the Service after changes constitutes acceptance of the
            revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900">12. Contact Us</h2>
          <p className="mt-2">
            If you have questions about these Terms, please contact us at{' '}
            <a
              href="mailto:support@getvorsa.ai"
              className="text-orange-600 hover:text-orange-500 underline"
            >
              support@getvorsa.ai
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  )
}
